name: 'Tabits Infra deployment'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
    - run: |  
            sudo sed -i 's?{secrets.access_key}?${{ secrets.access_key }}?g' main.tf
            sudo sed -i 's?{secrets.secret_key}?${{ secrets.secret_key }}?g' main.tf
            curl https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip -O -J -L
            sudo unzip terraform_0.14.11_linux_amd64.zip && rm terraform_0.14.11_linux_amd64.zip
            chmod 777 -R *
            terraform init
            terraform validate
            terraform plan