name: 'Tabits Infra deployment'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}

    permissions:
      pull-requests: write
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
    - run: |  
            sudo sed -i 's?{secrets.access_key}?${{ secrets.access_key }}?g' variables.tf
            sudo sed -i 's?{secrets.secret_key}?${{ secrets.secret_key }}?g' variables.tf
            curl https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip -O -J -L
            sudo unzip terraform_0.14.11_linux_amd64.zip && rm terraform_0.14.11_linux_amd64.zip
            terraform init
            terraform validate
            terraform plan
  apply:
    needs: [plan]
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
    environment:
      name: main
    permissions:
      pull-requests: write
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
    - run: |  
            sudo sed -i 's?{secrets.access_key}?${{ secrets.access_key }}?g' variables.tf
            sudo sed -i 's?{secrets.secret_key}?${{ secrets.secret_key }}?g' variables.tf
            curl https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip -O -J -L
            sudo unzip terraform_0.14.11_linux_amd64.zip && rm terraform_0.14.11_linux_amd64.zip
            terraform init
            terraform validate
            terraform apply --auto-approve
  destroy:
    needs: [plan]
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
    environment:
      name: main-destroy
    permissions:
      pull-requests: write
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
    - run: |  
            sudo sed -i 's?{secrets.access_key}?${{ secrets.access_key }}?g' variables.tf
            sudo sed -i 's?{secrets.secret_key}?${{ secrets.secret_key }}?g' variables.tf
            curl https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip -O -J -L
            sudo unzip terraform_0.14.11_linux_amd64.zip && rm terraform_0.14.11_linux_amd64.zip
            terraform init
            terraform validate
            terraform destroy --auto-approve

